name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Todoist tasks list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rxcod9/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          TODOIST_LENGTH: ${{ secrets.TODOIST_LENGTH }}
